language: python
python: "3.3"
install:
  - wget http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh
  - yes | bash lilypond-2.18.2-1.linux-64.sh
  - export PATH=~/lilypond:$PATH
script: nosetests
