#!/bin/bash

set -e

pylint \
  --reports n \
  --indent-string="  " \
  --disable=missing-docstring \
  --disable=too-many-public-methods \
  --disable=too-few-public-methods \
  --disable=invalid-name \
  *.py
